apiVersion: v1

kind: Pod

metadata: 
  name: calculator-app
  labels:
    app: calculator 
spec:
  containers:
  - name: calculatorpythonapp
    image: cloudcommandclassroom/calculatorimage:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
